<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ZefaIA.LLM</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ZefaIA.Core\ZefaIA.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
  </ItemGroup>
</Project>
