<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageReference Include="System.Reactive" Version="6.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\ZefaIA.Persistence\ZefaIA.Persistence.csproj" />
    <ProjectReference Include="..\..\src\ZefaIA.Core\ZefaIA.Core.csproj" />
  </ItemGroup>
</Project>
